# **Data representations for Neural Networks**
- nd-Array = tensor
- count number of opening brickets [[[ == number dimension, rank, axis

**Scalars (0D tensors)**



In [1]:
import numpy as np

a = np.array(25)
print(a)
print(a.ndim)
print(a.shape)

# OD Tesnor, 0 Rank Tensor

25
0
()


**Vectors (1D tensors)**

In [ ]:
a = np.array([1,3,4,9,6])
print(a)
print("Dimension",a.ndim)
print("Shape",a.shape)

# 1D Tensor, 1 Rank Tensor (tot dimensions), Vector, 1Axes Tensor 
# 5 rank vectors

[1 3 4 9 6]
Dimension 1
Shape (5,)


**Matrices (2D tensors)**

In [6]:
a=np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])

print(a)
print("Dimension",a.ndim)
print("Shape",a.shape)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
Dimension 2
Shape (3, 5)


**3D tensors and higher-dimensional tensors**

In [ ]:
a = np.arange(1,46).reshape((3,3,5))

print(a)
print("Dimension",a.ndim)
print("Shape",a.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]
Dimension 3
Shape (3, 3, 5)


In [7]:
a = np.zeros((2,2,2,2))

print(a)
print("Dimension",a.ndim)
print("Shape",a.shape)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
Dimension 4
Shape (2, 2, 2, 2)


In [ ]:
a = np.ones((2,2,2,2,2))

print(a)
print("Dimension",a.ndim)
print("Shape",a.shape)

[[[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]



 [[[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]


  [[[1. 1.]
    [1. 1.]]

   [[1. 1.]
    [1. 1.]]]]]
Dimension 5
Shape (2, 2, 2, 2, 2)


# Example

In [ ]:
# hundred students and 3 marks of each student
a= [100, 3]
display(np.shape(a))
display(np.ndim(a))


# hundred students and 3 marks of each student for 4 weeks
b= [100, 4, 3]
display(np.shape(b))
display(np.ndim(b))

# hundred students for 4 weeks in 2 semesters and 3 marks of each student
x= [100, 4, 2, 3]
display(np.shape(x))
display(np.ndim(x))

(2,)

1

(3,)

1

(4,)

1

## Broadcasting

In [8]:
x= np.random.random((64,3,32,10))
y=np.random.random((32,10))

display(np.shape(x))
display(np.shape(y))

z=np.maximum(x,y)
display(np.shape(z))


(64, 3, 32, 10)

(32, 10)

(64, 3, 32, 10)

## Tensor Reshaping

In [ ]:
x = np.zeros((300,20))
x=np.transpose(x)
print(x.shape)

(20, 300)
